//
// Created by meow on 2/13/23.
//

#ifndef SPA_SRC_SPA_SRC_SP_EXTRACTOR_CONCRETE_EXTRACTORS_STATMENTLISTEXTRACTOR_H_
#define SPA_SRC_SPA_SRC_SP_EXTRACTOR_CONCRETE_EXTRACTORS_STATMENTLISTEXTRACTOR_H_

class StatmentListExtractor {

};

#endif //SPA_SRC_SPA_SRC_SP_EXTRACTOR_CONCRETE_EXTRACTORS_STATMENTLISTEXTRACTOR_H_
