//
// Created by meow on 2/13/23.
//

#ifndef SPA_SRC_SPA_SRC_SP_EXTRACTOR_CONCRETE_EXTRACTORS_USESEXTRACTOR_H_
#define SPA_SRC_SPA_SRC_SP_EXTRACTOR_CONCRETE_EXTRACTORS_USESEXTRACTOR_H_

class UsesExtractor {

};

#endif //SPA_SRC_SPA_SRC_SP_EXTRACTOR_CONCRETE_EXTRACTORS_USESEXTRACTOR_H_
