name: Auto Autotester Run

on: push

env:
    BUILD_TYPE: Release

jobs:
  valgrind-check:
    name: Run auto autotester
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3

      - name: Setup CCache
        run: sudo apt-get install -y ccache

      - name: Cache Build directory
        uses: actions/cache@v3
        with:
          key: ${{ github.head_ref || github.ref_name }}-build-cache-spa
          path: |
            ./Team30/Code30/build

      - name: Setup Build Folder
        working-directory: ./Team30/Code30
        run: |
          cmake -E make_directory ./build

      - name: Generate CMake Project
        working-directory: ./Team30/Code30/build
        run: |
          sudo /usr/sbin/update-ccache-symlinks
          export PATH="/usr/lib/ccache:$PATH"
          export CCACHE_DIR="./build-cache"
          CC=clang CXX=clang++ cmake ../ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Compile Autotester
        working-directory: ./Team30/Code30/build
        run: cmake --build . --target autotester --config ${BUILD_TYPE} -j 2

      - name: Run Auto Autotester
        working-directory: ./Team30
        run: python3 Tests30/auto-autotester.py ./Code30/build/src/autotester/autotester ./Tests30/target-queries
