name: Linux CI Build

on: push

env:
    BUILD_TYPE: Release
    CCACHE_DIR: ${{ github.workspace }}/Team30/Code30/build/build-cache
    CCACHE_BASEDIR: ${{ github.workspace }}/Team30/Code30

jobs:
  build-linux:
    runs-on: [self-hosted, Linux]
    timeout-minutes: 30
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - name: Lint CPP
        run: |
          cpplint --filter=-legal/copyright --recursive ./Team30/Code30/src/spa/src

      - name: Setup CCache
        run: sudo apt-get install -y ccache

      - name: Setup Build Folder
        working-directory: ./Team30/Code30
        run: |
          cmake -E make_directory ./build
          cmake -E make_directory ./build/build-cache

      - name: Generate CMake Project
        working-directory: ./Team30/Code30/build
        run: |
          sudo /usr/sbin/update-ccache-symlinks
          export PATH="/usr/lib/ccache:$PATH"
          ccache --set-config=cache_dir=${CCACHE_DIR}
          ccache --set-config=base_dir=${CCACHE_BASEDIR}
          ccache --set-config=hash_dir=false
          CC=clang CXX=clang++ cmake ../ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Restore Build Cache
        uses: actions/cache/restore@v3
        with:
          key: build-cache-${{ github.head_ref || github.ref_name }}-${{github.sha}}
          path: ./Team30/Code30/build/build-cache
          enableCrossOsArchive: true
          restore-keys: |
            build-cache-${{ github.head_ref || github.ref_name }}-
            master-scheduled-build-cache

      - name: Show CCache Stats
        run: |
          ccache -v -s

      - name: Compile SPA
        working-directory: ./Team30/Code30/build
        run: |
          cmake --build . --target unit_testing --config ${BUILD_TYPE} -j 2
          cmake --build . --target integration_testing --config ${BUILD_TYPE} -j 2
          cmake --build . --target autotester --config ${BUILD_TYPE} -j 2

      - name: Show CCache Stats
        run: |
          ccache -v -s

      - name: Save Build Cache
        uses: actions/cache/save@v3
        with:
          key: build-cache-${{ github.head_ref || github.ref_name }}-${{github.sha}}
          path: ./Team30/Code30/build/build-cache

      - name: Test Unit Testing
        working-directory: ./Team30/Code30/build
        run: |
          ./src/unit_testing/unit_testing -r console -d yes --order lex

      - name: Test Integration Testing
        working-directory: ./Team30/Code30/build
        run: |
          ./src/integration_testing/integration_testing -r console -d yes --order lex
