name: CI Commit Build

on: push

env:
    BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: self-hosted
    timeout-minutes: 30
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - name: Lint CPP
        run: |
          cpplint --filter=-legal/copyright --recursive ./Team30/Code30/src/spa/src

      - name: Setup CCache
        run: sudo apt-get install ccache
        
      - name: Cache Build directory
        uses: actions/cache@v3
        with:
          key: ${{ github.head_ref || github.ref_name }}-build-cache-spa
          path: |
            ./Team30/Code30/build

      - name: Setup Build Folder
        working-directory: ./Team30/Code30
        run: |
          cmake -E make_directory ./build

      - name: Generate CMake Project
        working-directory: ./Team30/Code30/build
        run: |
          sudo /usr/sbin/update-ccache-symlinks
          export PATH="/usr/lib/ccache:$PATH"
          export CCACHE_DIR="./build-cache"
          CC=clang CXX=clang++ cmake ../ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Compile SPA
        working-directory: ./Team30/Code30/build
        run: |
          cmake --build . --target unit_testing --config ${BUILD_TYPE} -j 2
          cmake --build . --target autotester --config ${BUILD_TYPE} -j 2

      - name: Test Unit Testing
        working-directory: ./Team30/Code30/build
        run: |
          ./src/unit_testing/unit_testing -r console -d yes --order lex
