name: CI Commit Build

on: push

env:
    BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: self-hosted
    timeout-minutes: 30
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Build Folder
        working-directory: ./Team30/Code30
        run: |
          cmake -E make_directory ./build

      - name: Generate CMake Project
        working-directory: ./Team30/Code30/build
        run: |
          cmake ../ -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

      - name: Compile SPA
        working-directory: ./Team30/Code30/build
        run: |
          cmake --build . --target unit_testing --config ${BUILD_TYPE} -j 2
          cmake --build . --target autotester --config ${BUILD_TYPE} -j 2
