name: Coverage

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: Coverage mode
        options: 
        - summary
        - html
        required: true
  push:

env:
    BUILD_TYPE: Release
    CCACHE_DIR: ${{ github.workspace }}/Team30/Code30/build/build-cache
    CCACHE_BASEDIR: ${{ github.workspace }}/Team30/Code30
    ACTION_MODE: html

jobs:
  coverage-check:
    name: Run Coverage
    runs-on: [self-hosted, Linux, compute]

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3

      - name: Setup Build Folder
        working-directory: ./Team30/Code30
        run: |
          cmake -E make_directory ./build

      - name: Generate CMake Project
        working-directory: ./Team30/Code30/build
        run: |
          sudo /usr/sbin/update-ccache-symlinks
          export PATH="/usr/lib/ccache:$PATH"
          CC=clang CXX=clang++ cmake ../ -DCODE_COVERAGE=1

      - name: Compile and Coverage Summary
        working-directory: ./Team30/Code30/build
        if: env.ACTION_MODE == 'summary'
        run: make cov-report-unit_testing -j 4

      - name: Compile and Coverage HTML
        working-directory: ./Team30/Code30/build
        if: env.ACTION_MODE == 'html'
        run: make cov-unit_testing -j 4

      - name: Upload HTML
        if: env.ACTION_MODE == 'html'
        uses: actions/upload-artifact@v3
        with:
          path: ./Team30/Code30/build/coverage/unit_testing
          retention-days: 1
        
