name: Cleanup Actions Caches (All)
on: workflow_dispatch

jobs:
  cleanup:
    runs-on: [self-hosted, Linux, chore]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Cleanup Caches
        run: |          
          REPO=${{ github.repository }}

          echo "Fetching list of cache key"
          cacheKeysForRepo=$(gh actions-cache list -R $REPO -L 90 | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForRepo
          do
              gh actions-cache delete $cacheKey -R $REPO --confirm
          done
          echo "Done 1"

          echo "Fetching list of cache key"
          cacheKeysForRepo=$(gh actions-cache list -R $REPO -L 90 | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForRepo
          do
              gh actions-cache delete $cacheKey -R $REPO --confirm
          done
          echo "Done 2"

          echo "Fetching list of cache key"
          cacheKeysForRepo=$(gh actions-cache list -R $REPO -L 90 | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForRepo
          do
              gh actions-cache delete $cacheKey -R $REPO --confirm
          done
          echo "Done 3"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
