name: Master CI Build

# on: push
on:
  schedule:
    - cron: "0 22 * * *"

env:
    BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 6
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Build Folder
        shell: bash
        working-directory: ./Team30/Code30
        run: cmake -E make_directory ./build

      - name: Generate CMake Project
        working-directory: ./Team30/Code30/build
        shell: bash
        run: cmake -A x64 .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      
      - name: Compile SPA
        shell: bash
        working-directory: ./Team30/Code30/build
        run: |
          cmake --build . --target unit_testing --config ${BUILD_TYPE} -j 4
          cmake --build . --target integration_testing --config ${BUILD_TYPE} -j 4
          cmake --build . --target autotester --config ${BUILD_TYPE} -j 4

  build-darwin:
    runs-on: macos-latest
    timeout-minutes: 6
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Build Folder
        working-directory: ./Team30/Code30
        run: cmake -E make_directory ./build

      - name: Generate CMake Project
        working-directory: ./Team30/Code30/build
        run: cmake ../ -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      
      - name: Compile SPA
        working-directory: ./Team30/Code30/build
        run: |
          cmake --build . --target unit_testing --config ${BUILD_TYPE} -j 4
          cmake --build . --target integration_testing --config ${BUILD_TYPE} -j 4
          cmake --build . --target autotester --config ${BUILD_TYPE} -j 4

  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup CCache
        run: sudo apt-get install ccache

      - name: Cache Build directory
        uses: actions/cache@v3
        with:
          key: master-scheduled-build-cache
          path: |
            ./Team30/Code30/build

      - name: Setup Build Folder
        working-directory: ./Team30/Code30
        run: |
          cmake -E make_directory ./build

      - name: Generate CMake Project
        working-directory: ./Team30/Code30/build
        run: |
          sudo /usr/sbin/update-ccache-symlinks
          export PATH="/usr/lib/ccache:$PATH"
          export CCACHE_DIR="./build-cache"
          CC=clang CXX=clang++ cmake ../ -DCMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Compile SPA
        working-directory: ./Team30/Code30/build
        run: |
          cmake --build . --target unit_testing --config Release -j 4
          cmake --build . --target integration_testing --config Release -j 4
          cmake --build . --target autotester --config Release -j 4

      - name: Test Unit Testing
        working-directory: ./Team30/Code30/build
        run: |
          ./src/unit_testing/unit_testing -r console -d yes --order lex

      - name: Test Integration Testing
        working-directory: ./Team30/Code30/build
        run: |
          ./src/integration_testing/integration_testing -r console -d yes --order lex
