name: Valgrind CI Check

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Binary to perform valgrind checks on
        options: 
        - unit_testing
        - integration_testing
        - autotester
        required: true

env:
    BUILD_TYPE: Release

jobs:
  valgrind-check:
    name: Run Valgrind
    runs-on: ubuntu-latest

    steps:
      - name: Setup Valgrind
        run: sudo apt-get install -y valgrind ccache

      - name: Cache Build directory
        uses: actions/cache@v3
        with:
          key: ${{ github.head_ref || github.ref_name }}-build-cache-spa
          path: |
            ./Team30/Code30/build

      - name: Setup Build Folder
        working-directory: ./Team30/Code30
        run: |
          cmake -E make_directory ./build

      - name: Generate CMake Project
        working-directory: ./Team30/Code30/build
        run: |
          sudo /usr/sbin/update-ccache-symlinks
          export PATH="/usr/lib/ccache:$PATH"
          export CCACHE_DIR="./build-cache"
          CC=clang CXX=clang++ cmake ../ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Compile SPA
        working-directory: ./Team30/Code30/build
        run: cmake --build . --target ${{github.events.inputs.action}} --config ${BUILD_TYPE} -j 2

      - name: Run Valgrind
        working-directory: ./Team30/Code30/build
        run: valgrind ./src/${{github.events.inputs.action}}/${{github.events.inputs.action}}
